Add missing line feeds to end of files
Clang complained about missing line feeds at the end of files:

    efi/efi.h:213:17: error:
    no newline at end of file [-Werror,-Wnewline-eof]
      213 | #endif // _EFI_H

Signed-off-by: Heinrich Schuchardt <heinrich.schuchardt@canonical.com>